# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: PipAuthenticate@1
  inputs:
    feedUrl: 'https://dev.azure.com/SimhaP/'
    artifactFeeds: 'SimhaP'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
    architecture: 'x64'

- task: PythonScript@0
  inputs:
    scriptSource: 'inline'
    script: |
      rows = 7
      for i in range(1, rows - 1):
          print(" " * (rows - 1) + " * " *i)
    arguments: 'z = 3+4i'